#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: What Is Bitcoin?

# Short bio or description (displayed in the header)
description:  Get started right with Bitcoin.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/we-use-coins-what-is-bitcoin.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: info@weusecoins.com
  facebook: weusecoins
  flickr:
  github: sunnankar/wuc-new
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: WeUseCoins
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: weusecoins
  googleplus: 107348049293492306722/posts

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: weusecoins

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-22253606-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://www.weusecoins.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""


# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: WeUseCoins Forum

# Short description (goes below the title; it will also be used in the RSS feed)
description: WeUseCoins forum for discussion on crypto-currency and blockchain technology.

# Your name, as you want it to appear underneath each post and in the footer
author: WeUseCoins

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
baseurl: /forum

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: https://www.weusecoins.com/forum

# Exclude system files
exclude: [.gitignore]

# The disqus shortname for your forum
disqus_shortname: weusecoins

# The public key for your disqus application
disqus_publickey: MfUcnIi9YQO2slHWW9c1jkMmu0FUb5CjE3bl5Dau4VMPEv4kDRJlH6kdrsbEOecA



#
# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet
highlighter: pygments
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
